language: python

sudo: false

python:
  - 2.7
  - 2.6
  - 3.6
  - 3.5
  - 3.4
  - 3.3
  - 3.2
  - pypy3
  - pypy

# whitelist
# gh-pages is otherwise ignored by Travis CI
# Use a regex to whitelist gh-pages and all branches
branches:
  only:
    - gh-pages
    - /.*/

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then travis_retry pip install unittest2; fi

script:
  - coverage run --source scripts/gpo_member_photos.py test/test_gpo_member_photos.py
  - python scripts/missing.py

after_success:
  - coverage report
  - coveralls
  - pip install pep8 pyflakes
  - pep8 scripts/*.py
  - pyflakes scripts/*.py

matrix:
  fast_finish: true
  allow_failures:
    - python: 2.6
    - python: 3.2
