language: python
cache: pip
sudo: false

matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.6
    - python: 3.5
    - python: 3.4
    - python: pypy3

# whitelist
# gh-pages is otherwise ignored by Travis CI
# Use a regex to whitelist gh-pages and all branches
branches:
  only:
    - gh-pages
    - /.*/

install:
  - pip install -r requirements.txt
  - pip install coveralls pyflakes

script:
  - coverage run  --append --source scripts test/test_gpo_member_photos.py
  - coverage run  --append --source scripts scripts/missing.py
  - pyflakes scripts/*.py

after_success:
  - coverage report
  - coveralls
  - pip install pycodestyle
  - pycodestyle scripts/*.py
